### ISSUE TITLE
[Question] Default username?

### ISSUE THREAD

**Issue by leshokunin** [hkalexling/Mango#132]
I just installed the Docker image and have it running. What's the default user name to login? I'm not seeing anything in the Docker documentation or the Wiki.

Do I have to create a user via the CLI?

**Comment by leshokunin** [comment]
Also, whenever I try to run a Terminal command with the Docker image, I get:
OCI runtime exec failed: exec failed: containter_linux.go:345: starting container process caused "exec: \"mango\": executable file not found in $PATH": unknown

The page at port 9000 does load properly though and shows me the login prompt.

**Comment by hkalexling** [comment]
Hi, the default username and password is printed in the console when you start Mango for the first time. Please see https://github.com/hkalexling/Mango#initial-login

For the second question, it looks like a Docker issue: https://github.com/docker/for-linux/issues/246. I can't reproduce it and it's not caused by Mango itself. You can try some of the most-upvoted solutions in the thread and see if they help.

**Comment by zezba9000** [comment]
What a totally stupid system.
It forces me to use nonsense password THEN breaks install because I tried passwords it didn't like.
