### ISSUE TITLE
[Feature Request] Manga-py for downloading manga

### ISSUE THREAD

**Issue by Zw012d** [hkalexling/Mango#160]
Would it be possible to integrate [manga-py](https://github.com/manga-py/manga-py) for downloading manga in some way like mangadex plugin in which we give link url and it uses manga-py to download and we only have to support one plugin for multiple manga sites and don't have to make changes in plugin if some sites break as it would be fixed from manga-py end itself like in case of mangadex v2 api changes.
 
![Screenshot 2021-02-06 212826](https://user-images.githubusercontent.com/76645315/107123283-b08e6c00-68c2-11eb-8286-f7c9c2a9eae8.png)

**Comment by hkalexling** [comment]
It's unlikely to happen because integrating manga-py would require a Python interpreter at run time. Mango is designed to be a self-contained application that you can just download and run, and I would like to keep it that way. 

If you prefer manga-py, you can always use it to download whatever you want and then read them in Mango.
