### ISSUE TITLE
Error Question: Unhandled exception: Unable to create directory: '/root/mango': File exists (File::AlreadyExistsError)

### ISSUE THREAD

**Issue by urcades** [hkalexling/Mango#179]
So I ran the install script located in the 'get started' script:

```
wget https://github.com/hkalexling/Mango/releases/latest/download/mango
chmod +x mango
./mango
```

And I receive the following error:

```
[INFO]    2021/03/18 02:52:51 | The DB directory /root/mango does not exist. Attempting to create it
Unhandled exception: Unable to create directory: '/root/mango': File exists (File::AlreadyExistsError)
  from ../usr/share/crystal/src/crystal/system/unix/dir.cr:60:13 in 'mkdir_p'
  from ../__w/Mango/Mango/src/storage.cr:38:7 in 'default'
  from ../__w/Mango/Mango/src/mango.cr:48:3 in '->'
  from ../usr/share/crystal/src/hash.cr:867:45 in '__crystal_main'
  from ../usr/share/crystal/src/crystal/main.cr:105:5 in 'main'
  from src/env/__libc_start_main.c:94:2 in 'libc_start_main_stage2'
```

The weird issue here is that when I actually look at `/root/mango`, there is no directory located here, only the binary.

Any idea what might be going on?

Thanks!

**Comment by hkalexling** [comment]
Hi, in Unix [everything is a file](https://en.wikipedia.org/wiki/Everything_is_a_file), and folders are just special files. You can't have two files (or folders for that matter) with the same filename, and that's why you got the error. Please move the binary to somewhere else (e.g., `/usr/local/bin`) and then run it.
