### ISSUE TITLE
[Question] Why is the database 2gb in size?

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#184]
![image](https://user-images.githubusercontent.com/17975351/112884408-c43e9d80-90cf-11eb-9f43-f7fc4e047f1d.png)
I don't understand how big it is. The covers are stored in the Uploads folder, so it shouldn't even be for that.

**Comment by hkalexling** [comment]
We do store the auto-generated thumbnails in the DB. The uploads folder stores user uploaded covers.

If you don't want the thumbnails, you can safely delete the `thumbnails` table from the DB, and set `thumbnail_generation_interval_hours` to `0` to disable the thumbnail generation.

**Comment by zFerry98** [comment]
I understand,
I do not think I will remove the thumbs, I would like to avoid finding the mango logo instead of the "preview" of the first page for the chapters and volumes that already have the cover inside.

But what advantage does it have over the competition (Komga, LANRaragi) to save them in the DB? Because the Komga DB with about 200 series, 32mb size and I have no problems (same as LANRaragi but he makes you choose the folder where to save the thumbs).
![image](https://user-images.githubusercontent.com/17975351/112977298-2b069a00-9156-11eb-9a34-83ef1e34aa63.png)
LANRaragi Thumbs folder (LANRaragi uses the same library as Komga, so they are two different servers that manage the exact same files).

Thanks anyway, mango remains the top of the 3 👍🔝

**Comment by hkalexling** [comment]
Oh, you won't see the Mango logo even if you delete the table. The table stores low-res thumbnails of the covers. If you delete the table, Mango would just take the first page of each archive (cbz/cbr) and use it as the cover. There are two reasons why we generate the thumbnails:

- the thumbnails are smaller in size than the original covers, so they load faster under a slow connection. 
- loading thumbnails from the DB is faster than reading the first page of archive files. 

But if you have good download speed and a fast disk you probably won't notice the difference. 

> But what advantage does it have over the competition (Komga, LANRaragi) to save them in the DB? 

I think it's easier to manage. It's unlikely for users to mess around with the thumbnails, so we can hide them in a DB file. When migrating the instance, they just need to move the DB file and don't need to worry about another folder. Also, the thumbnails are very small in size, so loading them won't be inefficient compared to loading them from the file system. We don't save the user-uploaded covers in DB, because these covers can be large. Loading large blobs from DB is slow. 

Perhaps in the future, we can allow users to choose whether they want thumbnails to be stored in DB or file system, but so far DB is working fine.
