### ISSUE TITLE
How to recover first login password

### ISSUE THREAD

**Issue by Chicken-DEV** [hkalexling/Mango#2]
I started the Mango Docker container but stopped it shortly after because one of my other containers had a crashed. Now I don't have the first login password or username. Is there a way to recover them?

**Comment by hkalexling** [comment]
You can delete the SQLite database from the docker container. It contains only login information, and on the next run, Mango would automatically create a new database and generate the initial username and password.

To delete the database, you can shell into the container using `docker exec -it mango /bin/bash` while it's running. The SQLite file should be at `/root/mango/mango.db`. If it's not there, it's probably because you modified the `docker-compose.yml` and the file is on your host system. In that case please provide the docker-compose file here.

**Comment by hkalexling** [comment]
I am closing this issue, but feel free to reopen it.
