### ISSUE TITLE
[Feature Request] Changing Display Name of Mangas and Cover Images

### ISSUE THREAD

**Issue by SomeGuyKai** [hkalexling/Mango#20]
Hello,

I was wondering if you would be able to add the option to change the display names on the Manga Homepage so we can change the name of a manga and it does not affect the file name on the server? Also the option to set a different image for the covers instead of pulling the first image in the zip/cbz file?

For example changing "Kidou Sensei Gundam Gaiden - The Blue Destiny" to "Gundam: The Blue Destiny"

![image](https://user-images.githubusercontent.com/61396159/77219832-7af45f00-6b07-11ea-99ea-36f6b03ddfd4.png)

Thanks for creating this btw.

**Comment by hkalexling** [comment]
Hi, thanks for the feature request!

> ... so we can change the name of a manga and it does not affect the file name on the server

May I know why you would prefer this instead of renaming the folders on your server? Is there any particular reason? Personally I feel that renaming the folders is a much easier solution.

> Also the option to set a different image for the covers instead of pulling the first image in the zip/cbz file

Yeah, I agree this would be a nice feature to have. It's not a small feature so let me think about it and plan carefully. I will keep this issue open and keep you updated.

**Comment by SomeGuyKai** [comment]
Morning or Afternoon,

Whatever option is easier for you to implement. I saw another post about renaming the files, and thought maybe another option could be raised. 

Thank you.

**Comment by hkalexling** [comment]
This feature is now available in [v0.3.0](https://github.com/hkalexling/Mango/releases/tag/v0.3.0). Thanks for the feature request!
