### ISSUE TITLE
[Question] speed up the loading of the home

### ISSUE THREAD

**Issue by zFerry98** [hkalexling/Mango#209]
As from the title, I would like to propose the possibility of drastically increasing the loading speed of the page "`http://host:port`" (the one that then loads as home).

This for 2 reasons:
1) With the extension for tachiyomi ([this one](https://github.com/tachiyomiorg/tachiyomi-extensions/tree/master/src/all/mango)), it fails with "timeout" as an error. This is because it actually takes more than 60 seconds to load my home page.
While loading the Library page takes a maximum of 15 seconds.

2) because it is actually very slow to load and this also affects the time from when you log in to when the home page is loaded.

Currently I have a library of 132 items (so the root folder contains 132 folders) of 210gb (25,782 files & 2,067 folders).
On HDD 6Tb sata 3 WD Blue 2021.
Mango is installed on WSL 1 with Ubuntu 20 and is v 0.21.0.

**Comment by hkalexling** [comment]
Sorry for the long delay! Yes Mango was not designed to work with large libraries, so I planned out #148 to fix this together with other performance issues (e.g., #118 and #186). I will be closing this since it's similar to #186. Please subscribe to the other issues to get updated.

The development has been slower because I am busy with other duties (I will be defending my PhD thesis at the end of this month), so I can't put in as much time as I want. Luckily the software is already in a usable state.
