### ISSUE TITLE
[Bug Report] DB migration failed

### ISSUE THREAD

**Issue by tr7zw** [hkalexling/Mango#223]
**Describe the bug**
I've tried updating from a dev build(2? weeks old, some time after #211(v0.22.0)) to the latest release(v0.23.0), and it just prints ``DB migration failed. The current version 12 does not exist in the versions list``, unable to start again. Had to delete the mango.db file. Not sure if this was overlooked in the release, or rather I screwed something up by switching between builds like that.

**Comment by hkalexling** [comment]
Hi, the `dev` branch is not stable and would occasionally have breaking changes. In this case, it was because the DB migration version 12 was deleted from `dev` in [this commit](https://github.com/hkalexling/Mango/commit/19735642722bb5d2370fcebf7ddc5c2897a2b9ef). The version 12 migration never existed in `master` so it only affects `dev` branch users.

In the original thread, you mentioned that you are using it in a separate container so hopefully you didn't lose any data?

In case someone else also run into this, you can easily resolve it by executing the following SQL queries in `mango.db`:

```sql
drop table subscription;
pragma user_version = 11;
```

**Comment by tr7zw** [comment]
Didn't use a separate container, but didn't lose any important data. Thanks for the response.
