### ISSUE TITLE
[Question] Is it possible to read from third party extension ?

### ISSUE THREAD

**Issue by BirdInFire** [hkalexling/Mango#291]
Hello, i would like to know if it possible to only read for these plugins ? (without prior download), to see if i can read and if i like download, of if it's mandatory to download to read.

Thanks for the answer.

**Comment by hkalexling** [comment]
No, with the plugins you can only download chapters. You can't just "stream" them without downloading.

May I know the use case of this? App-based readers (e.g., Tachiyomi) have this feature because most manga sites are not built for mobile consumption, and streaming the chapters to a dedicated mobile reader can improve the experience. On the other hand, if you are reading from Mango you are already on web/browser, so why not just read from the manga sites directly?

**Comment by BirdInFire** [comment]
> No, with the plugins you can only download chapters. You can't just "stream" them without downloading.
> 
> May I know the use case of this? App-based readers (e.g., Tachiyomi) have this feature because most manga sites are not built for mobile consumption, and streaming the chapters to a dedicated mobile reader can improve the experience. On the other hand, if you are reading from Mango you are already on web/browser, so why not just read from the manga sites directly?

Yeah but i use it to save the manga i like, but no stream mean i like you've said must rely on a third party website, i hoped to do both on the self hosted app.

thanks for the answer though :)
