### ISSUE TITLE
Bulk convert CBR to CBZ (workaround)

### ISSUE THREAD

**Issue by jaredlt** [hkalexling/Mango#41]
I see you have CBR support [already planned](https://github.com/hkalexling/Mango/projects/2). I have a quite a lot of CBR files so this is a bit of a blocker at the moment. As a workaround, I wrote a bash script to convert my library so I could get a better feel for how Mango will work. By default it will not delete the original files so it should be reasonably safe to use. Perhaps it may be useful to others :)

- [cbr2cbz.sh](https://gist.github.com/jaredlt/eef3ce973b6040f06396976314e9be60)

Not sure if this is the right place for it but figured I would post and you can decide if it's useful / should live somewhere else.

---

On a separate note about your future cbr support. I see you are planning to get the user to supply the path. One of the things I really like about Mango is that it comes as a single binary that 'just works'. I honestly don't know the detail but if there was a way to bundle the functionality directly into the app, without the need to specify an external dependency, I think it would really help more users to easily set Mango up. And probably less new Github issues of users asking why cbr is not working :) [unar](https://theunarchiver.com/command-line) (not unrar) that I found and am using in the bash script appears to be a re-implementation that is already available in many package managers. Not sure if it helps?

**Comment by hkalexling** [comment]
The challenging part about RAR is that it's a proprietary format so (unlike zip) there's no RAR reader/writer in the Crystal standard library. I couldn't find any shards for it either. 

A conversion script would indeed be nice to have! Let me test it a bit and then include it in the wiki.

I didn't know about `unar` and it looks promising 👍 . It supports other formats like 7zip, so with it Mango can have cb7 support as well. I don't think the `unar` binary is statically linked by default, so including it in the Mango binary might not work, but since it's open-source I can try to compile it statically. I will keep you updated!

**Comment by hkalexling** [comment]
I have tested the conversion script and it works great! It's now in the [Wiki](https://github.com/hkalexling/Mango/wiki/Workarounds#bulk-convert-cbr-to-cbz).

Unfortunately, I couldn't get `unar` to link statically, but I agree we should make the binary self-contained if possible. Instead of including a third party binary in the Mango binary, I think it makes more sense if we could wrap a C-based RAR extraction library (e.g., [libarchive](https://github.com/libarchive/libarchive)) as a Crystal shard and use it in Mango. I will try to work on it when I have the time.

I am closing this issue, but feel free to reopen it.

**Comment by hkalexling** [comment]
@jaredlt Just to keep you updated, I have added RAR/CBR support in [the dev branch](https://github.com/hkalexling/Mango/tree/dev) (thanks to the [libarchive](https://github.com/libarchive/libarchive) project). 

Since you mentioned that you have a lot of CBR files, it would be great if you could help to test it out! If you want, you can use the mango binary compiled by the [GitHub Action](https://github.com/hkalexling/Mango/actions/runs/119096729) (see the "Artifacts" section).

**Comment by jaredlt** [comment]
@hkalexling happy to help!

I get the following error when I run Mango:

```
Unhandled exception in spawn: RAR solid archive support unavailable. (Archive::Error)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
```

I can access the web interface but it shows 0 titles in the library.

As a side note, is there a way to run multiple instances of Mango with separate configs and dbs? It's not a big deal, but just wondered.

**Comment by hkalexling** [comment]
Thanks for testing it 👍. It looks like `libarchive` does not support [solid RAR archives](https://www.winrar-france.fr/winrar_instructions_for_use/source/html/HELPArcSolid.htm), and that's why you got the error. Where did you get your CBR files? Is it common for them to be solid?

> is there a way to run multiple instances of Mango with separate configs and dbs? 

Yes, see #21 . However, if you are serving the instances under the same domain/IP, the two instances will overwrite each other's login token in the browser cookies. 

Currently, the login token is always stored in the browser cookies under the key `token` (see https://github.com/hkalexling/Mango/blob/master/src/routes/main.cr#L27-L29). Perhaps we can include the port number in the key (say `token-9000`) so tokens from different ports will be stored separately.

**Comment by hkalexling** [comment]
Could you please set the log level to `debug` and test with [this build](https://github.com/hkalexling/Mango/actions/runs/120665603)? I've made it so that when it fails to read an archive, it logs the archive path and the detailed error message. You should be able to see how many of your CBR files are solid.

**Comment by hkalexling** [comment]
I checked some similar projects. [komga]() doesn't support solid RAR either ([source](https://github.com/gotson/komga/blob/master/komga/src/main/kotlin/org/gotson/komga/infrastructure/mediacontainer/RarExtractor.kt#L27)), and [LANraragi](https://github.com/Difegue/LANraragi) is using `libarchive` as well ([source](https://github.com/Difegue/LANraragi/blob/master/lib/LANraragi/Utils/Archive.pm#L18-L19)). I guess we can leave it like this and make it clear in the README or Wiki that solid RAR files are not supported.

**Comment by jaredlt** [comment]
> Where did you get your CBR files? Is it common for them to be solid?

Scattered across the internet :) It seems solid is not very common at all (only 3 archives were solid) and I agree that a clear message somewhere should suffice. The majority of errors were actually `Parsing filters is unsupported`. Admittedly most of the archives with errors are for comics, not manga, and all of them are quite old.

- `Archive error: Prefix found`: 3
- `Archive error: RAR solid archive support unavailable.`: 3
- `Archive error: Parsing filters is unsupported.`: 67
- `Archive error: Couldn't find directory end signature in the last 65KB`: 1

Attached full [debug.log](https://github.com/hkalexling/Mango/files/4710894/debug.log)

I was going to say that the `info` level logging isn't super clear as it says `File /path/file.cbr is corrupted or is not a valid archive. Ignoring it.` (you don't know exactly what the problem is). But I see in [#49](https://github.com/hkalexling/Mango/issues/49#issuecomment-636324740) you are looking to be more specific with the error messages regarding permissions. Will you also do the same regarding solid support etc?

You also mention displaying corrupted archives in the web interface. I think this will be really useful. Will this apply for all errors or unsupported archives? Basically, anything where the logger says `ignoring it`?

RE: multiple instances - thanks, I'm happy enough with how it is. It hasn't become painful to switch around so no need to prioritise the cookie `token` fix on my account.

**Comment by hkalexling** [comment]
Thanks a lot for investigating this! 

> Archive error: Parsing filters is unsupported.

This is due to an old bug in `libarchive` (see https://github.com/libarchive/libarchive/issues/373), and LANraragi has the same issue (https://github.com/Difegue/LANraragi/issues/165). Unfortunately, there's nothing much we can do :(

Regarding multiple instances, I have been thinking about it, and I think there's no harm in doing it. We just need to change a few lines, and it's a good workaround for #13. Supporting #13 would involve a lot of work and I am not ready to do it :P Will probably include it in v0.5.0 as well.
