### ISSUE TITLE
Unknown bug in scanner code causing scan to go on forever.

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#7]
When scanning a particular folder full of .cbz files, the scanner binds up.

The files do not have consistent names; some look like this:

xxx - Volume_01_[xxx].cbz

And some look like this:

xxx - Volume_27.cbz

The error thrown in terminal looks like this:
Unhandled exception in spawn: Couldn't find directory end signature in the last 65KB (Zip::Error)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???

Anything I should try, short of renaming everything?

**Comment by DuraMorte** [comment]
Renamed all files to look identical to my second example. No change.

**Comment by hkalexling** [comment]
It is not a naming problem, and I think the culprit here is that one of the `.cbz` files is corrupted.

Basically a `.cbz` file is just a zip archive containing some images, and all Mango (and any cbz reader) does is unzip the file in memory and read the content. When the file is corrupted or is not a valid zip file, it cannot be unzipped.

Can you try to unzip the files using external tools like `unzip` if you are using Unix? If you see an error message like the one below, it means the file is corrupted (see [this](https://askubuntu.com/questions/54904/unzip-error-end-of-central-directory-signature-not-found)).

> End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.

But I agree that the scanning process should not hang even when a corrupted file is present. In version 0.2.0 that I am working on, Mango would ignore any corrupted and invalid zip files when scanning the library. I will make a minor release soon to address this and a few other issues.

**Comment by hkalexling** [comment]
In [v0.1.2](https://github.com/hkalexling/Mango/releases/tag/v0.1.2), Mango would ignore the invalid files and log a warning message. Feel free to reopen this issue if needed.
