### ISSUE TITLE
Chapter sort issue with large volume/chapter counts

### ISSUE THREAD

**Issue by DuraMorte** [hkalexling/Mango#9]
When I imported a manwha with 500+ chapters, the sorting ordered them as follows:

1
10
100
101-109
11
110-119
12

etc. etc.

Would it be possible to have them listed in the proper order without having to prepend zeroes into the names?

**Comment by hkalexling** [comment]
This is the expected behavior when sorting by filename. It would be unreliable if Mango has to parse numbers from the filenames. For example, a filename might contain both volume and chapter numbers (e.g., `One-Punch Man Vol.02 Ch.120`). Sometimes people might have files with non-English filenames ,so parsing the number proceeding `Ch.` might also fail.

How do you think Mango should handle this?

**Comment by hkalexling** [comment]
I have been thinking about this, and one way to handle the problem to add an "intelligent sorter" to the list of sorting options. The intelligent sorter would attempt to parse the filenames to fetch the chapter/volume numbers and sort the files accordingly, and when it fails it can simply fall back to use the default filename sorting.

I will try to include this in the next release.

**Comment by hkalexling** [comment]
This is added in [v0.2.0](https://github.com/hkalexling/Mango/releases/tag/v0.2.0). The default sorting option for chapters is "Auto", which sorts files in the way you described. 

<img width="321" alt="Screen Shot 2020-03-13 at 4 32 39 PM" src="https://user-images.githubusercontent.com/7845831/76657456-4d784600-6548-11ea-8881-aef654c8afa9.png">

**Comment by DuraMorte** [comment]
Auto sort is working! My manwha displays correctly (after renaming the files as Volumes, as opposed to their original naming as Episodes).
Thank you for your hard work!
