### ISSUE TITLE
[Feature Request] Batch Mark Selected Improvements

### ISSUE THREAD

**Issue by DJScias** [hkalexling/Mango#97]
**Describe the solution you'd like**

**Desktop**
- Once you have one selected, just mark the whole "cover" area as "add to selection". 

**Mobile**
- Start the selection by long-pressing a cover and then every other cover press adds to selection

**Describe a small use-case for this feature request**

**Desktop**
For batch selection this would make it lots of easier. It's obvious that once there's one selection that when a user clicks on a second cover they don't want to start reading or mark progress, they just want to add to the already existing selection.

**Mobile**
The only way currently to select a cover here is by some workarounds, there's no "hover" effect you have on a mobile really so long-press would take care of this.

**Additional context**
An image to visualize what I mean by "whole cover area". Basically everything I've put lines on should work as an "add to selection" since once you've one selected it's obvious you want to continue to select more.
![image](https://user-images.githubusercontent.com/439655/90890184-c7471200-e3b9-11ea-8488-b00fe7349857.png)

**Comment by hkalexling** [comment]
Hey sorry for the long delay! In [v0.17.1](https://github.com/hkalexling/Mango/releases/tag/v0.17.1), the whole cover image is clickable once you've made a selection. This should improve the UX a bit.

For the long-press, I think it would be better to keep the current state because the different behavior on mobile would break the user expectation. I do have plans for official mobile apps, and I think I will use the long-press there. Anyway, thanks a lot for the request!
